version: "3.7"

services:
  database:
    image: postgres
    container_name: rentalx-database
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=ignite
      - POSTGRES_DB=rentalx
    volumes:
      - pgdata:/data/postgres

  redis:
    image: redis:alpine
    container_name: rentalx-redis
    ports:
      - 6379:6379

  # app:
  #   build: .
  #   container_name: rentalx-app
  #   ports:
  #     - 3333:3333
  #     - 9229:9229 # Debugger
  #   volumes:
  #     - .:/usr/app
  #   links:
  #     - database
  #   depends_on:
  #     - database

volumes:
  pgdata:
    driver: local
